---
- name: Install Common Services
  hosts: devices
  become: true

  vars_files:
    - "config/device-config.yml"

  tasks:
    - name: Set Authorized Key taken from file
      authorized_key:
        user: "{{ vars.ansible_user }}"
        state: present
        key: "{{ lookup('file', '~/.ssh/lbd_ed25519.pub') }}"

    - name: Add Python Repository
      apt_repository:
        repo: ppa:deadsnakes/ppa
        state: present
      when: ansible_distribution == "Ubuntu"

    - name: Update and upgrade apt packages
      become: true
      apt:
        upgrade: yes
        update_cache: yes
        cache_valid_time: 86400 #One day

    - name: Install common APT
      apt:
        name:
          - software-properties-common
          - net-tools
          - iw
        state: latest
        update_cache: true

    - name: Install Git
      apt:
        name: git
        state: latest
        update_cache: true

    - name: Clone Repository
      git:
        repo: "{{ vars.repository }}"
        dest: "{{ vars.device_directory }}"
        force: true
        update: true
        clone: true
      become: false

    - name: Copy Config Files
      copy:
        src: ../../config/
        dest: "{{ vars.device_directory }}/config/"

    - name: Copy Device Config Files
      copy:
        src: ../device-setup/
        dest: "{{ vars.device_directory }}/listener/device-setup/"

    - name: Install Ansible
      apt:
        name:
          - ansible
        state: latest
        update_cache: true

#    - name: Debug Distribution
#      debug:
#        msg: "{{ hostvars[inventory_hostname]['ansible_distribution'] }}"

    - name: Install Python 3.11
      apt:
        name:
          - python3.11
          - python3-pip
          - python3-virtualenv
        state: latest
        update_cache: true
      when: ansible_distribution == "Ubuntu"

#    - name: Install RaspberryPi GPIO Library
#      apt:
#        name: python3-rpi.gpio
#        state: latest
#        update_cache: true

    - name: Install RaspberryPi GPIO Library
      apt:
        name: python3-rpi.gpio
        state: latest
        update_cache: true
      when: ansible_distribution == "Ubuntu"

    - name: Install GPIO Zero
      apt:
        name: python3-gpiozero
        state: latest
        update_cache: true


#    ADD sudo pigpiod USER.

    - name: Install Dependencies
      pip:
          chdir: "{{ vars.device_directory }}"
          requirements: requirements.txt
          state: present
          virtualenv: "{{ vars.device_directory }}/venv"
      become: false
