---
- name: Install Common Services
  hosts: devices
  become: true

  vars_files:
    - "config/device-config.yml"

  tasks:
    - name: Install common APT
      apt:
        name:
          - software-properties-common
          - net-tools
          - iw
        state: latest
        update_cache: true

    - name: Install Git
      apt:
        name: git
        state: latest
        update_cache: true

    - name: Debug Distribution
      debug:
        msg: "{{ hostvars[inventory_hostname]['ansible_distribution'] }}"

    - name: Install Python 3.11 on Ubuntu
      apt:
        name:
          - python3.11
          - python3-pip
        state: latest
        update_cache: true
      when: ansible_distribution == "Ubuntu"

#    - name: Install Python 3.10 on Raspbian
#      apt:
#        name:
#          - python3.10
#          - python3-pip
#        state: latest
#        update_cache: true
#      when: ansible_distribution == "Debian"

    - name: Clone Repository
      git:
        repo: "{{ vars.repository }}"
        dest: "{{ vars.device_directory }}"
        force: true
        update: true
        clone: true
      become: false

    - name: Install RaspberryPi GPIO Library
      apt:
        name: python3-rpi.gpio
        state: latest
        update_cache: true

    - name: Install RaspberryPi GPIO Library
      apt:
        name: python3-rpi-lgpio
        state: latest
        update_cache: true
      when: ansible_distribution == "Ubuntu"

    - name: Install GPIO Zero
      apt:
        name: python3-gpiozero
        state: latest
        update_cache: true

    - name: Install Dependencies
      pip:
          chdir: "{{ vars.device_directory }}"
          requirements: requirements.txt
          state: present
      become: false
