---
- name: Install PHP Dependencies
  hosts: main-server
  become: true

  vars_files:
    - "config/device-config.yml"

  tasks:
    - name: Install DHCP Server
      apt:
        name:
          - isc-dhcp-server
          - dnsutils
          - hostapd
          - bind9
        state: latest
        update_cache: true
      notify:
        - Restart DHCP

    - name: Configure DHCP Server
      template:
        src: templates/dhcpd.conf.j2
        dest: /etc/dhcp/dhcpd.conf
        owner: root
        group: root
        mode: 0644
      notify:
        - Restart DHCP

    - name: Configure DHCP Port Listening
      template:
        src: templates/isc-dhcp-server.j2
        dest: /etc/default/isc-dhcp-server
        owner: root
        group: root
        mode: 0644
      notify:
        - Restart DHCP

    - name: Configure DHCP Port Listening
      template:
        src: templates/interfaces.j2
        dest: /etc/network/interfaces
        owner: root
        group: root
        mode: 0644
      notify:
        - Restart DHCP

    - name: Configure Wifi Access Config File
      template:
        src: templates/hostapd.conf.j2
        dest: /etc/hostapd/hostapd.conf
        owner: root
        group: root
        mode: 0644
      notify:
        - Restart HostAPD

    - name: Configure Wifi Access Config Setup
      template:
        src: templates/hostapd.j2
        dest: /etc/default/hostapd
        owner: root
        group: root
        mode: 0644
      notify:
        - Restart HostAPD

    - name: Setup Port Forwarding
      template:
        src: templates/sysctl.conf.j2
        dest: /etc/sysctl.conf
        owner: root
        group: root
        mode: 0644
      notify:
        - Restart HostAPD
        - Restart DHCP

    - name: Add Reserved IP Address
      template:
        src: templates/NetworkManager.conf.j2
        dest: /etc/NetworkManager/NetworkManager.conf
        owner: root
        group: root
        mode: 0644
      notify:
        - Restart HostAPD
        - Restart DHCP

    - name: Add Docker GPG apt Key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker Repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu kinetic stable
        state: present

    - name: Update apt and install docker-ce
      apt:
        name: docker-ce
        state: latest
        update_cache: true

    - name: Install Docker Module for Python
      pip:
        name:
          - docker
          - docker-compose

    - name: Configure the Linux kernel to allow IP forwarding
      sysctl:
        name: net.ipv4.conf.all.forwarding
        value: 1
        sysctl_set: true
        state: present

    - name: Change the policy for the iptables FORWARD policy from DROP to ACCEPT
      iptables:
        chain: FORWARD
        policy: ACCEPT
        state: present

    - name: Start Docker Compose Services
      community.docker.docker_compose:
          project_src: "{{ vars.device_directory }}"
          state: present

  handlers:
    - name: Restart DHCP
      service:
        name: isc-dhcp-server
        state: restarted
        enabled: true

    - name: Restart HostAPD
      service:
        name: hostapd
        state: restarted
        enabled: true