---
- name: Power Down Servers
  hosts: devices
  become: true
  gather_facts: false

  tasks:
    - name: Shutdown
      community.general.shutdown:
        msg: "Shut down initiated by Ansible"
        delay: 0
